### ISSUE TITLE
remove DOM when animation finish

### ISSUE THREAD

**Issue by suhaotian** [legomushroom/mojs#11]
Demo: http://jsbin.com/katevekawo
how to remove DOM when animate finish

**Comment by legomushroom** [comment]
Hey!

You can add `onComplete` callback on each `Burst` object, where you can remove it's el:

```javascript
var removeEl = function removeEl (node) { node.parentNode.removeChild(node); }

function anim(x, y) {
  new mojs.Burst({
    delay: 100,
    shape: 'circle',
    fill: ['deeppink', 'orange', 'skyblue'],
    x: x + 'px', y: y + 'px',
    onComplete: function () { removeEl(this.el); }
  });
}

```

[demo](http://jsbin.com/radume/)

But you probably don't want do create so many objects and touch DOM so frequently because it will bother `GC` and `DOM`. What you want to do is - create a pool of bursts and then reuse the same objects over and over.

[demo](http://jsbin.com/bemakuw)

I will probably add `destroy` lifecycle method in the future, but again it is not what you want to do whilst animating, since it will add CPU overhead and can cause flickering of your animation.

**Comment by suhaotian** [comment]
@legomushroom thanks!

**Comment by legomushroom** [comment]
related https://github.com/legomushroom/mojs/issues/62
