### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by bartvollebregt** [legomushroom/mojs#125]
First of all I'd like to thank you for your amazing work on this project @legomushroom.

I've been implementing mojs several times and so far it has been running very smoothly.

Lately I've been struggling a bit with performance issues. I've tried it in several browsers and operating systems but they all seem to lag a bit.

Here's the codepen: https://codepen.io/bvbridgevest/pen/GWNKza

It seems to lag a bit while zooming in. After that it's all very smooth.

**Comment by legomushroom** [comment]
Hey sorry about that, let me see.

**Comment by legomushroom** [comment]
The main issue with your code is that it creates some objects when the animation is being played - this occupies the main javascript thread and triggers the jank to appear since a browser can not fit the animation in `16ms` frame (60fps). This is a common recommendation for an animation - create objects in advance and only trigger `play` while animation runs. There is the demo refactored regarding this notion - [demo](https://codepen.io/sol0mka/pen/wJoLqM?editors=0010). I also added some `timelines` and `delays` instead of `setTimeout` in an attempt to keep code clear.
Please let me know.

**Comment by bartvollebregt** [comment]
Wow looks very smooth. Didn't know the combining on the timeline made such a big difference. 

It's a stripped down version of my code and I'm doing more that just the animations, which also needs to be delayed. That's why I used the timeout.

Is it also possible in this scenario to stop the floating animations without stopping the whole timeline?

**Comment by legomushroom** [comment]
Happy to help, you can use the `setTimeout` just make sure you don't create objects when an animation is running. You can have reference to the objects and do:

```javascript
setTimeout( ()=> {
  someReference.play();
}, delay  );
```

> Is it also possible in this scenario to stop the floating animations without stopping the whole timeline?

Nope, the animation controlled by the main timeline so everything will be closed. You can keep 2 timelines instead and stop only one of them.

**Comment by bartvollebregt** [comment]
I'm not sure if this is a continuation on the old performance issues or if I should create a new one, but since it's the same demo I figured I'd better post it here.

There seems to be something odd with the curve property. While using my own curves the function take 230ms per call. When using a standard easing function like 'quad.out' (not doing what I want, just for the example) it only take max 2 ms per call.

I've set up an example based on the previous codepen [here](https://codepen.io/bvbridgevest/pen/RVWKgz?editors=0010). The timings can be seen starting at line 30.

Thanks in advance!

Ps: not sure if you're receiving anything from these old issues. So just a /cc here to be sure: @legomushroom

**Comment by legomushroom** [comment]
Hey Bart, thanks for the issue.

The custom curve has a preprocessing step which intent to reduce computation time during animation. Because SVG path can be really complex, compared to `bezier curve`, this step means sampling an SVG path so has some overhead on initialization. You can have control over initialization time by controlling a number of samples taken (fewer samples - less performant it during animation) and precision ([options](https://github.com/legomushroom/mojs/blob/master/js/easing/path-easing.coffee#L8)).

Probably the most useful optimization here is to make sure you create and reuse just one instance of the path easing, this can drastically improve the performance: [demo](https://codepen.io/sol0mka/pen/RVrQYM?editors=0010).

Hope it makes sense, please let me know.

Cheers~
