### ISSUE TITLE
Having a onPathCompleted method ?

### ISSUE THREAD

**Issue by Jeremboo** [legomushroom/mojs#14]
Hi,

I test mo.js and I try to make a loop effect. 
Waiting for documentation, I discover the methods directly in your objects. And I can see onComplete(), onStart(), onFirstUpdate() ... 

But I did not find a method to listen the end of a loop when I use the repeat property. Because for my test (and I do not know if my approach is already good), I have many elements with the same Tween and I wanted called a function to initialise each at the end of the path and before the next animation.

If I'm not clear, you can still see my code here:
http://codepen.io/Jeremboo/pen/RWddjK

So, it would be interesting to have ` onPathCompleted() ` method ? Or go through a different logic maybe.

**Comment by legomushroom** [comment]
Hey @Jeremboo!

Sorry for the delay and thanks for the issue.

You are right. Tween should have both `onComplete` and `onRepeatComplete` callbacks, so there is a lack of the later right now. I can consider a `PR` if you want to submit one, not sure if you do because tween internal logic could be complex to start with. Anyways please let me know if you are planning to make one and have any questions.

Re: `current affairs`
You can add each tween to `Timeline`. If you will do so, `Timeline` will be capable of repeating `Tween`s, thus their `onComplete` callbacks will fire on each loop.
[Demo](http://codepen.io/sol0mka/pen/aa771df3a85644f800d1af8cc2edd6ce?editors=001).

There is one `bug` which I will fix shortly - callback can fire few times in this scenario.

If you want another tween to run after your `scale` one, you can make a `Timeline` inside `startMo` function, `add` the current tween and then `append` another tween to the inner `Timeline`. After that add the `inner` timeline to the `outer` timeline which would be capable of controlling all the nested  timelines and tweens.
[Demo](http://codepen.io/sol0mka/pen/aa771df3a85644f800d1af8cc2edd6ce?editors=001).

Thanks a lot!

**Comment by legomushroom** [comment]
@Jeremboo, nice transition and colors btw, `love it!`

**Comment by legomushroom** [comment]
@Jeremboo oops, the first demo link was wrong. Updated to the right one.

**Comment by Jeremboo** [comment]
Hi @legomushroom !

Thank you for your precise and reactive response ! Sorry by the way I could not keep up with your answers…

For the `onRepeatComplete`  callback, indeed I am not sure to be the best to make a `PR`. I prefer to leave it to another guru ;) 

And, when I checked your demos and tried to understand the `Timeline` uses,  I found this approach very playful !


I created another [Demo](http://codepen.io/Jeremboo/pen/epqgZW?editors=001) with what you showed me. There are two Timelines into one and the loop works. 

But when my `mainTimeline` is played for a second time, between my two `inner` timelines, the `scale` is initialized. I don’t know if it is an error in my code or not, because the first time this does not happen... 

Another issues about `Timeline` : 

- Can I restart manually a `Timeline` like `myTm.restart()` or `myTm.stop().play()` or again `myTM.play(0)` ?
- Can I start my timeline at a given time like `myTm.play(2)` ?

Because on [my first Demo](http://codepen.io/Jeremboo/pen/RWddjK) ( become a pile of spaghetti ) I have used Visus.js also and I would like to chain both.  ( Please do not check my code I must rewrite it now with `Timeline` ! ).


Thank you again for the time you have spent for answering me !

**Comment by legomushroom** [comment]
@Jeremboo hi, sorry for the long reply.
 - I have completely rewritten the tweening engine, so it now has the `onRepeatComplete` callback out of the box.
 - You can restart the timeline with `replay` method.
 - To start the timeline with a time `shift`, just pass the time (milliseconds) to the `play` method:
```javascript
   var tween = new mojs.Tween;
   tween.play(  2000 ); // 2 seconds in ms
```
 - Or alternitelely you can do:

```javascript
     var tween = new mojs.Tween;
     tween.setProgress( 0.5 ).play(); // 2 seconds in ms
```

Please refer to the [Tween API](https://github.com/legomushroom/mojs/blob/master/api/index.md#tweens) for more info.
New `mojs` link on CDN: https://cdn.jsdelivr.net/mojs/0.265.6/mo.min.js
