### ISSUE TITLE
How can we sequence the animation indefinite. 

### ISSUE THREAD

**Issue by DeshpandeBoy** [legomushroom/mojs#154]
If .then(){....} is used for the sequencing how can I make the entire animation repeat indefinitely?

**Comment by brudoku** [comment]
.then({...
 onComplete(){
    timeline.replay()
  }

**Comment by thewolf** [comment]
here is the almost infinite version:

const timeline = new mojs.Timeline({
  repeat: Number.MAX_VALUE,
});

**Comment by thewolf** [comment]
or you can try this infinite version:

const timeline = new mojs.Timeline({
  repeat: Number.POSITIVE_INFINITY
});

**Comment by DeshpandeBoy** [comment]
@thewolf  & @brudoku I tried it's not working.

**Comment by thewolf** [comment]
@DeshpandeBoy that's stragne because it works for me:
https://codepen.io/thewolf/pen/dVemPy

Timeline extends Tween which have the repeat property: https://github.com/legomushroom/mojs/blob/master/js/tween/timeline.babel.js
https://github.com/legomushroom/mojs/blob/master/api/tweens/tween.md

anyway, I am glad you found a solution
