### ISSUE TITLE
Add class name

### ISSUE THREAD

**Issue by misha-marinenko-official** [legomushroom/mojs#192]
For example: 
```js
const polygon = new mojs.Shape({
  shape:        'polygon',
  className:        '.animation',
  points:       5,
  stroke:       '#A8CABA',
  scale:        { 0 : 1.5 },
  angle:        { 0 : 180 },
  fill:         { '#721e5f' : '#a5efce' },
  radius:       25,
  duration:     1200,
  easing:       'sin.out'
}).then ({
  stroke:       '#000',
  angle:        [-360],
  scale:        0,
  easing:       'sin.in'
});

```
:
```html
<div class="mojs-shape animation">
...
</div>
```

**Comment by xavierfoucrier** [comment]
Hi @misha-marinenko-official,

There is already a property to manage the html class attribute, called `className`, that do the job: https://github.com/legomushroom/mojs/blob/master/api/shape.md#shape.

Are you expecting that this attribute **should be renamed**?

Note that historically the `class` keyword was reserved in javascript, so it was impossible to use it as a property name, that's why @legomushroom choose to name this property `className`.

Best regards :wink:

**Comment by misha-marinenko-official** [comment]
I'm forgot about this! Thanks.
