### ISSUE TITLE
on interaction gives "(intermediate value).run is not a function"

### ISSUE THREAD

**Issue by fungw** [legomushroom/mojs#44]
Hi,

Love the product, and the explanations you give in the docs are key. But there seems to be an issue with library where it is no longer runnable. 

Anyone experiencing the same problem? As I suspect that this isn't a problem on my side, but a major problem regarding the library? If not, it'd be great if someone could explain to me what is acting up that makes the library not runnable on my side? 

As a side note, it was working fine, without any change of code up until recently. Currently, nothing works.

**Comment by legomushroom** [comment]
@fungw hi! Thanks for the issue and sorry about that.

It happens for you because the library got a large update for tweening engine, with breaking API changes so `run` method is not available anymore. To make your code work you have to lock the version of the `mojs` to previous ones (before 0.265.6) - you can find the older versions hosting of your choice (jsDelivr, bower, npm).

Alternatively, you can find the new APIs [here](https://github.com/legomushroom/mojs/blob/master/api/index.md) and use the new syntax. I hope you will love the new ones as I do. These ones can be considered `locked` and probably will never changed. Not sure what module you use and how you do it, but you probably want to suppress the `run` method with `play` or `replay` ones.

Sorry again for inconvenience, the new tutorials will be released just tomorrow - you are early bird with the change :)  Cheers

**Comment by legomushroom** [comment]
@fungw oh yeah, almost forgot, if you are using `mojs` a lot - you might like the [MojsPlayer](https://github.com/legomushroom/mojs-player) - that's a debugger tool that helps you to craft long mojs sequences. It works with the new version (0.265.6) tho.

**Comment by fungw** [comment]
@legomushroom 

Thanks for the quick response!

Apologies for being slightly ignorant in this case, I noticed your commits in the past week but wasn't sure so I thought I would ask.

MojsPlayer, I will check it out, thanks again.

++ keep up the solid work man

**Comment by legomushroom** [comment]
Thanks! Happy to help!
