### ISSUE TITLE
Unable to set random distance radius for burst in master build

### ISSUE THREAD

**Issue by Errvald** [legomushroom/mojs#49]
In ``0.174.4`` I could set ``randomAngle`` + ``randomRadius`` to make the end burst non circular. Can't seem to find a way to do this in the master build.

**Comment by legomushroom** [comment]
@Errvald hi, thanks for the issue! I think I know what you mean but I have to be sure. Could you please make a sample? There is codepen with `v0.174.4` installed to fork for you: http://codepen.io/sol0mka/pen/1306e1a432bfbcc1c4aaf71faa5fef8e?editors=0010

**Comment by Errvald** [comment]
Here's an example:
http://codepen.io/errvald/pen/rLANYA?editors=0010

**Comment by legomushroom** [comment]
@Errvald thanks! there is the same sample with annotations regarding new syntax: http://codepen.io/sol0mka/pen/oLrNdg?editors=0010 .

The new syntax was introduced to make the API more consistent with other modules and to make it much more flexible. This new syntax could be considered `locked` and will not change anymore. You can find the full API reference here:  https://github.com/legomushroom/mojs/blob/master/api/burst.md . I hope you will like it the same I do. It might be confusing at first when you will want to switch to the new one, but, believe me, you will find it more comfortable after you will spend a bit time with it.

Also, these two tutorials can help you to understand the new syntax and why exactly it shaped like that: [shape](http://mojs.io/tutorials/shape/) and [burst](http://mojs.io/tutorials/burst/). I gave you 2 tutorials because technically, the `burst` is merely particle emitter that emits `shapes`.

Hope it helps, please let me know if you have any questions or difficulties!

**Comment by Errvald** [comment]
@legomushroom Thanks a lot for the commented sample!

Yeah I much prefer the new syntax, ``pathScale`` was the option I was looking for!

**Comment by legomushroom** [comment]
@Errvald great, happy to help!
