### ISSUE TITLE
Binding Element to Starting Point for Animation

### ISSUE THREAD

**Issue by zfrisch** [legomushroom/mojs#87]
Hey there!

This is probably a dull question, but I was mocking up a CodePen for a blog post, started muddling around with mojs for awhile(I _may_ have gotten a little sidetracked, haha), and while tinkering I was wondering if there was a way to bind an animation to a specific element? As in just to designate a start point always from that element, wherever it may be. 

http://codepen.io/zfrisch/pen/YpvbZE?editors=1010 

In the code I created a helper object to do this with methods that would return the coordinates of whatever Pokemon and then just tuned the coordinates to the left and top properties when I started the animations, but I wasn't sure if there was a built-in way to do this.

**Comment by legomushroom** [comment]
Hi, Zak!

Thanks for the issue, awesome effects! I think you did it right, you have the animation and `tune` the animation to coordinates whatever your object is currently at.

Another approach is to use `parent` property that expects an `HTMLElement` that your effect will be placed in, so you might want to wrap your `<img />`s with an  `inline-block` and `position: relative` element and send it to the `parent` property of the effect [demo](http://codepen.io/sol0mka/pen/ZBjexm?editors=0010). Of course, with this approach, you will have `two` instances of the same effect instead of one that you have and reuse right now, but you can make a helper function that will bootstrap the effect for you and return the object back. [demo](http://codepen.io/sol0mka/pen/oYMZQb?editors=0010). 

Hope it helps, please let me know if you have any questions.

Cheers! // @zfrisch

**Comment by zfrisch** [comment]
Excellent! I was looking at the parent property but wasn't positive how to use it. The demo made it super clear! Thank you for being so responsive! 

By the way, awesome work on this library so far! I'm not a pro at SVG graphics, but mojs feels very natural to work with!

**Comment by legomushroom** [comment]
Happy to help! Thanks for the kind feedback and your support! 👍  🎉
