### ISSUE TITLE
Cancel or modify animation while playing

### ISSUE THREAD

**Issue by meriadec** [legomushroom/mojs#90]
Hi, and great work!

I'm currently testing multiple animations libraries, for a project with many user interactions. For some animations, we have the need to cancel / modify animations properties while animating (e.g: modify direction of a moving block, reacting to user interaction).

So, I'm guessing if it is possible with mo.js, or maybe it is not the use case.

Here is a gif to illustrate the problem ([see codepen](http://codepen.io/anon/pen/WoYzaB?editors=0010)):

![tween](https://cloud.githubusercontent.com/assets/315259/21226780/58070e4c-c2d7-11e6-9f2e-7a4f6d7dbee8.gif)

(edit: the square duplication at the end of gif is only due to image encoding)

**Comment by legomushroom** [comment]
Hi Meriadec,

Thanks for such details issue! You can do that with `Shape`/`Burst` module by use of `pause`, `stop` or even `reset` methods to stop the animation(see [shape apis](https://github.com/legomushroom/mojs/blob/master/api/shape.md)) and the `tune` new properties on the module - [demo](http://codepen.io/sol0mka/pen/ZBmVqJ?editors=0010).

As for the `Html` animation, it might be a little more tedious, actually I thought we have `tune` method on `Html` but seems we don't so you want to do the same but instead of tuning, you want to create new `Html` module - [demo](http://codepen.io/sol0mka/pen/eBQbXe?editors=0010). 

Please let me know if you have any questions.

**Comment by meriadec** [comment]
Thanks. I'm gonna experiment with that!

**Comment by legomushroom** [comment]
Happy to help!
