### ISSUE TITLE
strokeDashoffset not synchronize with animation duration

### ISSUE THREAD

**Issue by ariona** [legomushroom/mojs#98]
Why is the strokeDashoffset delta is not synchronized with the animation duration. I tried to animate the strokDashoffset but it already finished in the middle of animation and then back to -100%.

http://codepen.io/ariona/pen/xgxMpN

**Comment by legomushroom** [comment]
Hi, Rian!

Thanks for the issue, sorry for the inconvenience!

You do it from `-100%` to `100%` so it seems legit for me - it animates from `invisible(-100%)` to `invisible(100%)`. If you want to keep it visible at the end, you can do animation from `invisible(100%)` to `visible(0%)` [demo](http://codepen.io/sol0mka/pen/bgNyge). Notice that in my demo it starts from positive `100%` due to `Safari's` strokedash bug with negative numbers.

Hope it helps! Pretty code btw ;) Please let me know.

**Comment by legomushroom** [comment]
Rian,

Just thought maybe you would like to see the `stagger` wrapper function, it is nice for such effects - [demo](http://codepen.io/sol0mka/pen/EZazmp?editors=0010). There is the second demo with the same effect: [demo](http://codepen.io/sol0mka/pen/zNxQEL?editors=0010). Hope they convey the idea of stagger wrapper good enough.

Cheers!

**Comment by ariona** [comment]
Oh i see, i didn't think about that earlier. Thanks.
That's really cool effect.

**Comment by ariona** [comment]
@legomushroom any idea to change the stroke position (like, inside, outside & center)?

**Comment by legomushroom** [comment]
Rian, SVG doesn't support that. Could be possible when we will implement renderer: SVG/canvas/webgl option.

**Comment by sdras** [comment]
SVG2 would if it ever gets off the ground... I'll try to find where you can vote on it and post back.

**Comment by legomushroom** [comment]
Sarah, you are right. We can't expect it will get any stable among browsers earlier than few years thought. Thinking maybe we can polyfill this.

**Comment by sdras** [comment]
Yeah, Amelia did mention that they'd be making some polyfills, I had previous asked for one for the mesh gradient (you would do amazing things with that @legomushroom), I'll ask if there was progress made there.
